package com.vw.lang.sink.java.link;

import com.vw.lang.sink.java.VWMLObjectsRepository;
import com.vw.lang.sink.java.entity.VWMLEntity;

/**
 * Each module's linking component (generated by processor) implements this interface
 * @author ogibayev
 *
 */
public class VWMLLinkage {

	/**
	 * Interprets object identified by id as object identified by interpretingId
	 * @param id
	 * @param interpretingId
	 * @throws Exception
	 */
	public void interpretAs(Object id, Object interpretingId) throws Exception {
		VWMLEntity obj = (VWMLEntity)VWMLObjectsRepository.instance().get(id);
		VWMLEntity interpretingObj = (VWMLEntity)VWMLObjectsRepository.instance().get(interpretingId);
		obj.setInterpreting(interpretingObj);
	}
}
