package com.vw.lang.processor.model.builder.specific;

import java.io.File;
import java.io.FileWriter;
import java.util.Set;

import com.vw.lang.processor.model.builder.VWMLModelBuilder;
import com.vw.lang.processor.model.builder.VWMLModuleInfo;
import com.vw.lang.sink.ICodeGenerator.StartModuleProps;
import com.vw.lang.sink.java.code.JavaCodeGenerator.JavaModuleStartProps;
import com.vw.lang.sink.java.module.VWMLModule;

/**
 * Acts as bridge between generated sources and interpreter 
 * @author ogibayev
 *
 */
public class VWML2JavaInterpreterFactoryBuilder {
	private static String s_className = "VWML2JavaInterpreterFactory";
	private static String s_caption = "/** \r\n*  This code was generated by VWML processor \r\n*  Description: Bridge between generated sources and interpreter \r\n*  Author: %s \r\n*  Date  : %s \r\n*/";
	private static String s_bridgePackageSuffix = "bridge";
	
	public void build() throws Exception {
		buildCode();
	}
	
	private void buildCode() throws Exception {
		final int PACKAGE_INDEX = 0x1;
		final int IMPORT_INDEX  = 0x2;
		final int BODY_INDEX    = 0x4;
		JavaModuleStartProps projProps = (JavaModuleStartProps)VWMLModelBuilder.instance().getProjectProps();
		
		String[] code = {
				// 1. caption
				prepareCaption(projProps) + "\r\n\r\n",
				// 2. package
				null,
				null,				
				"public class " + s_className + " {\r\n",
				null,
				"};\r\n"
		};
		
		Set<String> vwmlModules = VWMLModelBuilder.getProcessedModules();
		if (vwmlModules == null) {
			throw new Exception("there are no any processed modules; test cases can't be created");
		}
		// usually first module defines project's properties
		String bridgePackage = null;
		int prefixRRange = projProps.getModulePackage().lastIndexOf(".");
		if (prefixRRange == -1) {
			bridgePackage = s_bridgePackageSuffix;
		}
		else {
			bridgePackage = projProps.getModulePackage().substring(0, prefixRRange) + "." + s_bridgePackageSuffix;
		}
		String fullSourcePath = projProps.getSrcPath() + "/" + bridgePackage.replaceAll("\\.", "/");
		// generates package
		code[PACKAGE_INDEX] = "package " + bridgePackage + ";\r\n\r\n";
		// generates import section
		code[IMPORT_INDEX] = prepareImports(vwmlModules);
		// generates body section
		code[BODY_INDEX] = prepareBody(vwmlModules);
		File f = new File(fullSourcePath);
		if (!f.exists() && !f.mkdirs()) {
			throw new Exception("couldn't create directory; directory is '" + fullSourcePath + "'");
		}
		FileWriter fw = new FileWriter(fullSourcePath + "/" + s_className + ".java");
		for(String section : code) {
			fw.write(section);
		}
		fw.close();
	}
	
	/**
	 * Returns caption constructed from modules' properties
	 * @param props
	 * @return
	 */
	protected String prepareCaption(StartModuleProps props) throws Exception {
		return String.format(s_caption, ((JavaModuleStartProps)props).getAuthor(), "");
	}
	
	private String prepareImports(Set<String> vwmlModules) {
		String imports = "";
		// prepare imports
		imports += "import " + VWMLModule.class.getName() + ";\r\n\r\n";		
		for(String name : vwmlModules) {
			VWMLModuleInfo mi = VWMLModelBuilder.getModuleInfo(name);
			JavaModuleStartProps props = (JavaModuleStartProps)mi.getProps();
			imports += "import " + props.getModulePackage() + "." + props.getActualModuleName() + ";\r\n";
		}
		imports += "\r\n";
		return imports;
	}
	
	private String prepareBody(Set<String> vwmlModules) {
		String body = prepareModulesDeclaration(vwmlModules);
		body += "\tprivate static " + s_className + " s_instance = new " + s_className + "();\r\n\r\n\tprivate " + s_className + "() {\r\n\t}\r\n\r\n";
		body += "\tpublic static " + s_className + " instance() {\r\n\t\treturn s_instance;\r\n\t}\r\n\r\n";
		body += "\tpublic VWMLModule[] getModules() {\r\n\t\treturn modules;\r\n\t}\r\n";
		return body;
	}
	
	private String prepareModulesDeclaration(Set<String> vwmlModules) {
		boolean firstIteration = true;
		String modulesDeclaration = "";
		modulesDeclaration += "\tprivate VWMLModule modules[] = { ";
		for(String name : vwmlModules) {
			if (!firstIteration) {
				modulesDeclaration += ", ";
			} 
			else {
				firstIteration = false;
			}
			VWMLModuleInfo mi = VWMLModelBuilder.getModuleInfo(name);
			JavaModuleStartProps props = (JavaModuleStartProps)mi.getProps();
			modulesDeclaration += "new " + props.getActualModuleName() + "()";
		}
		modulesDeclaration += " };\r\n\r\n";
		return modulesDeclaration;
	}
}
